<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="differential_drive_robot">

  <!-- Load Configurable Parameters -->
  <xacro:property name="wheel_separation" value="0.2"/> <!-- meters -->
  <xacro:property name="wheel_diameter" value="0.065"/> <!-- meters -->
  <xacro:property name="robot_length" value="0.35"/> <!-- meters -->
  <xacro:property name="robot_width" value="0.25"/> <!-- meters -->
  <xacro:property name="base_link_z_offset" value="0.05"/> <!-- meters -->
  <xacro:property name="base_link_height" value="0.004"/> <!-- meters -->
  <xacro:property name="imu_link_length" value="0.015"/> <!-- meters -->
  <xacro:property name="imu_link_width" value="0.03"/> <!-- meters -->
  <xacro:property name="imu_link_height" value="0.003"/> <!-- meters -->
  <xacro:property name="imu_link_position_height" value="0.01"/> <!-- meters -->
  <xacro:property name="lidar_link_height" value="0.1"/> <!-- meters -->

  <!-- Base Link -->
  <link name="base_link">
    <visual>
      <geometry>
        <box size="${robot_length} ${robot_width} ${base_link_height}"/>
      </geometry>
    </visual>
  </link>

  <!-- Base Footprint -->
  <link name="base_footprint">
  <visual>
      <geometry>
      <box size="0.001 0.001 0.001"/> <!-- Minimal visual representation -->
      </geometry>
  </visual>
  </link>
  
  <joint name="base_footprint_to_base_link" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <origin xyz="0 0 ${base_link_z_offset}" rpy="0 0 0"/>
  </joint>


  <!-- Wheels -->
  <xacro:macro name="wheel" params="name x y z">
    <link name="${name}">
      <visual>
        <geometry>
          <cylinder length="0.01" radius="${wheel_diameter / 2}"/>
        </geometry>
        <!-- <material name="black"/> -->
      </visual>
      <collision>
        <geometry>
          <cylinder length="0.01" radius="${wheel_diameter / 2}"/>
        </geometry>
      </collision>
    </link>
    <joint name="${name}_joint" type="continuous">
      <parent link="base_link"/>
      <child link="${name}"/>
      <origin xyz="${x} ${y} ${z}" rpy="1.5707 0 0"/> <!-- Adjust rpy for wheel rotation axis -->
      <axis xyz="0 1 0"/>
    </joint>
</xacro:macro>

  <!-- IMU Link -->
  <link name="imu_link">
    <visual>
      <geometry>
        <box size="${imu_link_length} ${imu_link_width} ${imu_link_height}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </visual>
  </link>
  <joint name="imu_joint" type="fixed">
    <parent link="base_link"/>
    <child link="imu_link"/>
    <origin xyz="0 0 ${imu_link_position_height + base_link_z_offset / 2}" rpy="0 0 3.14"/>
  </joint>

  <!-- Lidar Link -->
  <link name="lidar_link">
    <visual>
      <geometry>
        <cylinder length="0.02" radius="0.05"/>
      </geometry>
    </visual>
  </link>
  <joint name="lidar_joint" type="fixed">
    <parent link="base_link"/>
    <child link="lidar_link"/>
    <origin xyz="0 0 ${lidar_link_height}" rpy="0 0 0"/>
  </joint>

  <!-- Instantiate Wheels -->
<xacro:wheel name="left_wheel" x="0" y="${-wheel_separation / 2}" z="${-base_link_z_offset / 2}"/>
<xacro:wheel name="right_wheel" x="0" y="${wheel_separation / 2}" z="${-base_link_z_offset / 2}"/>

</robot>